### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by marklawton** [axcheron/cisco_pwdecrypt#2]
Hi 

getting the below error, been trying to figure it out but not getting any joy, any  advice / help appreciated

-----error below -------

$ python3 cisco_pwdecrypt.py -u <PASSWORD> -d passwords.txt
[*] Bruteforcing 'type 5' hash...

	Found 10000 passwords to test.
	Testing: <PASSWORD>
Traceback (most recent call last):
  File "cisco_pwdecrypt.py", line 173, in <module>
    type5_decrypt(args.type5, args.dict)
  File "cisco_pwdecrypt.py", line 121, in type5_decrypt
    if split_pwd[1] == '1':
IndexError: list index out of range

**Comment by marklawton** [comment]
managed to fix the issue

**Comment by axcheron** [comment]
Can you give me more details ?

**Comment by marklawton** [comment]
sorry was in a rush preivously, for some reason the passlib had not installed correctly, i had to install manually using pip3 install passlib. after this i ran the example from your readme file and all seemed to start working 

cheers

M

**Comment by axcheron** [comment]
Perfect. If there is any issue with the code, feel free to contact me. Enjoy :)
