### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tars01** [axcheron/cisco_pwdecrypt#4]
Hi, I'm trying to use this for md5 but having the following issue. Any idea why this might be happening? 

Thanks

```
[*] Bruteforcing 'type 5' hash...

        Found 14344391 passwords to test.
        Testing: $1$VWmp
        Hash Type = MD5
        Salt = VWmp
Traceback (most recent call last):
  File "cisco_pwdecrypt.py", line 173, in <module>
    type5_decrypt(args.type5, args.dict)
  File "cisco_pwdecrypt.py", line 128, in type5_decrypt
    print("\tHash = %s\n" % split_pwd[3])
IndexError: list index out of range
```

When I put in a print statement to see what split password is (split_pwd)

It's coming back with: ['', '1', 'VWmp']

So slice 3 is out of range. It's almost like it's not passing the whole md5 string in the script. This is the md5 I am passing to the script: \$1\$VWmp$vnpGGorzU9NOGkw9qHnMS0

**Comment by axcheron** [comment]
Hi !

As the hash format contains "**$**" signs, you have to escape them :

`$ python3 cisco_pwdecrypt.py -u "\$1\$VWmp\$vnpGGorzU9NOGkw9qHnMS0" -d passwords.txt`
